# Generated by Django 2.2.1 on 2019-05-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_no', models.IntegerField()),
                ('car_name', models.CharField(max_length=64)),
                ('team_name', models.CharField(max_length=128)),
                ('univ_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SensorInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=32)),
                ('input_data', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_car', to='laptime.Car')),
            ],
        ),
        migrations.CreateModel(
            name='LapTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_time', models.DurationField(blank=True, null=True)),
                ('lap_status', models.CharField(choices=[('IN', 'IN_LAP'), ('STAY', 'STAY_OUT'), ('OUT', 'OUT_LAP')], max_length=4)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car', to='laptime.Car')),
                ('end_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_time', to='laptime.SensorInput')),
                ('start_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='start_time', to='laptime.SensorInput')),
            ],
        ),
    ]
