# Generated by Django 2.2.1 on 2019-06-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptime', '0002_auto_20190606_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptime',
            name='lap_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
