# Generated by Django 2.2.1 on 2019-06-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptime', '0004_auto_20190606_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorinput',
            name='input_data',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
